import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";

export default function Home() {
  const { greeting } = useSelector((state: any) => state.app);
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1
          onClick={() => {
            dispatch({
              type: "app/setGreeting",
              payload: {},
            });
            window.navigator.vibrate(500);
          }}
          className={styles.title}
        >
          Welcome to Saba.js!
        </h1>

        <p className={styles.description}>{greeting}</p>
      </main>
    </div>
  );
}
